# Generated by Django 4.1.1 on 2022-10-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpage_webranking_blogpage_weburl'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='weburl2',
            field=models.URLField(blank=True),
        ),
    ]
