# Generated by Django 4.1.1 on 2022-10-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpage_options_alter_blogpage_weburl2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={},
        ),
    ]
