# Generated by Django 4.1.1 on 2022-10-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ['-webranking']},
        ),
    ]
