# Generated by Django 4.1.1 on 2022-10-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='webgroupranking',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
