# Generated by Django 4.1.1 on 2022-10-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogindexpage_webgroupranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogSecondPage',
        ),
    ]
