# Generated by Django 4.1.1 on 2022-10-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_delete_blogsecondpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={},
        ),
    ]
