# Generated by Django 4.1.1 on 2022-10-13 11:31

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_webpage_categories_remove_webpage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='body',
            field=wagtail.fields.StreamField([('project1', wagtail.blocks.StructBlock([('pname', wagtail.blocks.CharBlock()), ('pintro', wagtail.blocks.CharBlock()), ('purl', wagtail.blocks.CharBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('biography', wagtail.blocks.RichTextBlock())])), ('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], use_json_field=True),
        ),
    ]
