# Generated by Django 4.1.1 on 2022-10-14 16:16

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_githubtrendingpage_githubtrendingtagindexpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubtrendingpage',
            name='body',
            field=wagtail.fields.StreamField([('githubcodes', wagtail.blocks.StructBlock([('codename', wagtail.blocks.CharBlock()), ('codeintro', wagtail.blocks.CharBlock()), ('codeurl', wagtail.blocks.CharBlock())]))], use_json_field=True),
        ),
    ]
