# Generated by Django 4.1.1 on 2022-10-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_githubtrendingpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='webranking',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='weburl2',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(verbose_name='发布日期：'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='weburl',
            field=models.CharField(blank=True, max_length=250, verbose_name='网址：'),
        ),
    ]
