# Generated by Django 4.1.1 on 2022-10-15 07:34

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_blogpage_webranking_remove_blogpage_weburl2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='正文：'),
        ),
    ]
