# Generated by Django 4.1.1 on 2022-10-15 11:00

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_blogpage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubtrendingpage',
            old_name='tags',
            new_name='githubtags',
        ),
        migrations.AlterField(
            model_name='githubtrendingpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_itemss', to='blog.githubtrendingpage'),
        ),
    ]
