# Generated by Django 4.1.1 on 2022-10-15 11:14

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_rename_tags_githubtrendingpage_githubtags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubtrendingpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.githubtrendingpage'),
        ),
    ]
